In [2]:
import numpy as np

In [3]:
lst1=[1,2,3,4,5]
lst2=[2,4,6,8,10]
lst3=[3,6,9,12,15]

ar=np.array([lst1,lst2,lst3])

In [4]:
ar

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15]])

In [5]:
type(ar)

numpy.ndarray

In [6]:
ar.shape

(3, 5)

In [7]:
ar.reshape(15,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [ 3],
       [ 6],
       [ 9],
       [12],
       [15]])

In [8]:
ar.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  2],
       [ 4,  6,  8],
       [10,  3,  6],
       [ 9, 12, 15]])

In [9]:
ar[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15]])

In [10]:
ar[2,:]

array([ 3,  6,  9, 12, 15])

In [11]:
ar[1:,:2]

array([[2, 4],
       [3, 6]])

In [13]:
ar[1,4]

10

In [15]:
ar[:2:4]

array([[1, 2, 3, 4, 5]])